//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace englishProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comment()
        {
            this.comment1 = new HashSet<comment>();
        }
    
        public int commentId { get; set; }
        public string userId { get; set; }
        public string commentNote { get; set; }
        public System.DateTime commentDate { get; set; }
        public int commentExceptId { get; set; }
        public Nullable<int> commentReplyId { get; set; }
        public int commentKind { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comment1 { get; set; }
        public virtual comment comment2 { get; set; }
    }
}
