//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace englishProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EnglishProjectDBEntities : DbContext
    {
        public EnglishProjectDBEntities()
            : base("name=EnglishProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Box> Box { get; set; }
        public virtual DbSet<IrregularVerb> IrregularVerb { get; set; }
        public virtual DbSet<Level> Level { get; set; }
        public virtual DbSet<Word> Word { get; set; }
        public virtual DbSet<levelUserProgress> levelUserProgress { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<UserDetail> UserDetail { get; set; }
        public virtual DbSet<Score> Score { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<log> log { get; set; }
    
        public virtual ObjectResult<userProggress_Result> userProggress(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<userProggress_Result>("userProggress", userIdParameter);
        }
    }
}
