//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace englishProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class levelUserProgress
    {
        public int progressId { get; set; }
        public string userId { get; set; }
        public int levelId { get; set; }
        public int puan { get; set; }
        public int star { get; set; }
        public int boxId { get; set; }
        public int targetScore { get; set; }
    }
}
